# Stage 1 — Build Vite app
FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Stage 2 — Serve with Nginx
FROM nginx:stable

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 5173
EXPOSE 80
