# FROM python:3.10-slim

# # Prevent Python from writing .pyc files
# ENV PYTHONDONTWRITEBYTECODE=1
# ENV PYTHONUNBUFFERED=1

# WORKDIR /app

# # Install system deps if compiler is needed
# RUN apt-get update && apt-get install -y --no-install-recommends \
#     build-essential \
#     && apt-get clean \
#     && rm -rf /var/lib/apt/lists/*

# # Copy ONLY requirements first (for caching)
# COPY requirements.txt .

# RUN pip install --no-cache-dir -r requirements.txt

# # Copy only backend code (not your venv, not your frontend)
# COPY . .

# EXPOSE 8000

# CMD ["uvicorn", "app.server:app", "--host", "0.0.0.0", "--port", "8000"]

################################################################################################3

# FROM python:3.10-slim

# ENV PYTHONDONTWRITEBYTECODE=1
# ENV PYTHONUNBUFFERED=1

# WORKDIR /app

# # Install just pip + runtime libraries (tiny!)
# RUN apt-get update && apt-get install -y --no-install-recommends \
#     libsqlite3-0 \
#     && apt-get clean \
#     && rm -rf /var/lib/apt/lists/*

# COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt

# COPY . .

# EXPOSE 8000

# CMD ["uvicorn", "app.server:app", "--host", "0.0.0.0", "--port", "8000"]

################################################################################################3

# ============================
# STAGE 1: build dependencies
# ============================
FROM python:3.10-alpine AS builder

WORKDIR /app

RUN apk add --no-cache build-base

COPY requirements.txt .
RUN pip install --no-cache-dir --prefix=/install -r requirements.txt

COPY . .

# ============================
# STAGE 2: final slim runtime
# ============================
FROM python:3.10-alpine

WORKDIR /app

COPY --from=builder /install /usr/local
COPY --from=builder /app /app

EXPOSE 8000

CMD ["uvicorn", "app.server:app", "--host", "0.0.0.0", "--port", "8000"]

